name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set Git user
        run: |
          git config --global user.email "jdominion123@gmail.com"
          git config --global user.name "DOMINION-JOHN1"

      - name: Add and commit large files with Git LFS
        run: |
          git track git lfs track "filenames.pkl"
          git add .
          git commit -m "Add filenames.pkl using Git LFS"

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Dominion-John:$HF_TOKEN@huggingface.co/spaces/Dominion-John/goody_goody_fashion_store main
