name: Update_Model

on:
  schedule:
    - cron: "47 15 * * *"

jobs:
  update_model:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
    
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run python script
        run: |
          git config user.email "jdominion123@gmail.com"
          git config user.name "DOMINION-JOHN1"
          python run_file.py

      - name: Convert and Push as LFS
        run: |
          git lfs track "filepath.pkl"
          git add .gitattributes
          git add filepath.pkl
          git commit -m "Update filepath.pkl"
          git push origin HEAD:refs/heads/main
