name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Git user
        run: |
          git config --global user.email "jdominion123@gmail.com"
          git config --global user.name "DOMINION-JOHN1"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://$HF_TOKEN@huggingface.co/spaces/Dominion-John/goody_goody_fashion_store
          git add . 
          git commit -m "Your commit message"
          git push origin
